version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directories:
      - "/build"
      - "/"
    schedule:
      interval: "daily"
