# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/persona-id/query-sniper/

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: all
  disable:
    - exhaustruct
    - godox # FIXME
    - lll
    - testpackage
    - varnamelen
    - wsl # deprecated in favor of wsl_v5
  exclusions:
    generated: lax
    paths:
      - builtin$
      - examples$
      - third_party$
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

  settings:
    cyclop:
      max-complexity: 30
      package-average: 0
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/goforj/godump
            - github.com/go-sql-driver/mysql
            - github.com/lmittmann/tint
            - github.com/persona-id/query-sniper/internal
            - github.com/spf13/pflag
            - github.com/spf13/viper
          files:
            - $all
            - "!$test"
          list-mode: strict
    funlen:
      lines: -1
      statements: 65
    gocognit:
      min-complexity: 40
    goconst:
      min-occurrences: 5
    govet:
      enable-all: true
    ireturn:
      allow:
        - anon
        - empty
        - error
        - stdlib
    tagliatelle:
      case:
        rules:
          json: snake

run:
  tests: true
