# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

archives:
  - builds_info:
      group: root
      owner: root
    files:
      - src: configs/config.yaml
        strip_parent: true
      - src: configs/credentials.yaml
        strip_parent: true
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: main
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s
      - -w
    main: ./cmd/query-sniper
    mod_timestamp: "{{ .CommitTimestamp }}"

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  use: github

checksum:
  name_template: "checksums.txt"

dockers:
  - build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.licenses=BSD-3-Clause"
      - "--label=org.opencontainers.image.source=https://github.com/persona-id/query-sniper"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.vendor=Persona Identities (https://withpersona.com)"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    dockerfile: build/Dockerfile
    extra_files:
      - configs/config.yaml
      - configs/credentials.yaml
    image_templates:
      - "ghcr.io/persona-id/{{.ProjectName}}:latest"
      - "ghcr.io/persona-id/{{.ProjectName}}:{{ .Tag }}"
    skip_push: false

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

release:
  footer: >-
    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

report_sizes: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

upx:
  - enabled: false
    ids: [main]
    goos: [linux]
    goarch: [amd64]
    compress: best
    lzma: true
    brute: true
