services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:dev-1.25-bookworm
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - .:/workspace:cached
      - ../tmp/certs:/certs
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
    depends_on:
      - dev-db-primary
      - dev-db-replica0
      - dev-db-replica1
    command: sleep infinity
    environment:
      - MYSQL_PS1=\u@\h>\_
