---
# Path to the crednetials secret
credentials: configs/credentials.yaml

log_level: DEBUG

# List of databases to watch and various configuration options for them. The login creds
# are stored in the file defined above, and the keys to each database entry must match.
databases:
  us1_primary:
    address: 192.168.194.152:6033
    schema: persona-web-us1
    replica_lag_limit: 50s
    hll_limit: 50
    long_query_limit: 60s
    interval: 1s
  us1_replica0:
    address: 192.168.194.152:6033
    schema: persona-web-us1
    replica_lag_limit: 60s
    hll_limit: 60
    long_query_limit: 120s
    interval: 5s
  us2_primary:
    address: 192.168.194.152:6033
    schema: persona-web-us2
    replica_lag_limit: 70s
    hll_limit: 70
    long_query_limit: 60s
    interval: 1s
  us2_replica0:
    address: 192.168.194.152:6033
    schema: persona-web-us2
    replica_lag_limit: 80s
    hll_limit: 80
    long_query_limit: 120s
    interval: 5s
