---
# Path to the crednetials secret
credentials: configs/credentials.yaml

log_level: DEBUG

# Note: all limits are in seconds and need the 's' suffix
default_config: &default_config
  # run the check every 1 second
  interval: 1s
  # kill queries that have been running for more than 10 seconds
  long_query_limit: 10s

# List of databases to watch and various configuration options for them. The login creds
# are stored in the file defined above, and the keys to each database entry must match.
databases:
  dev-primary:
    address: db-primary:3306
    schema: test
    <<: *default_config
  dev-replica:
    address: db-replica:3306
    schema: test
    <<: *default_config
