---
# Path to the credentials files; this should be mounted in the pod as a secret from GCSM.
credential_file: configs/credentials.yaml

# Anything in this block is global, but can be overridden by the database-specific configs.
# NB: all limits are in seconds, and MUST have the 's' suffix.
default_config: &default_config # run the check every 1 second
  interval: 1s
  # kill queries that have been running for more than X seconds
  long_query_limit: 2s
  # kill transactions that have been running for more than X seconds
  long_transaction_limit: 10s
  # whether to run in dry run mode; if true, the sniper will only log the queries
  # and transactions that are exceeding the thresholds, but not kill anything
  dry_run: true
  # SSL configuration (optional, depending on the database needs).
  # Valid combinations are:
  #   - CA-only mode: Just ssl_ca for encrypted connections without client auth
  #   - Mutual TLS mode: All three (ssl_ca, ssl_cert, ssl_key) for mutual authentication
  #   - Invalid partial combinations (cert without CA, etc.) result in an error
  # ssl_cert: /etc/mysql/certs/dev-db-primary-cert.crt
  # ssl_key: /etc/mysql/certs/dev-db-primary-key.key
  # ssl_ca: /etc/mysql/certs/dev-db-primary-ca.crt

# List of databases to watch, and various configuration options for them. The login creds
# are stored in the file defined above, and the keys to each database entry must match.
databases:
  db-dev-primary:
    <<: *default_config
    address: dev-db-primary
    port: 3306
    schema: web-us1

  db-dev-replica0:
    <<: *default_config
    address: dev-db-replica0
    port: 3306
    schema: web-us1
  db-dev-replica1:
    <<: *default_config
    address: dev-db-replica1
    port: 3306
    schema: web-us1
    interval: 10s
    long_query_limit: 60s
    long_transaction_limit: 120s

# Logging configuration; this sets up slog
log:
  # The slog logger level to use. Valid options are "TRACE", "DEBUG", "INFO", "WARN", "ERROR", and "FATAL".
  level: INFO
  # The format of the log output. Valid options are "json" and anything else. If value isnt json, log output will be plain text and colorized.
  format: json
  # Whether to include the caller in the log output.
  include_caller: false
