---
# Auth credentials for the configured databases.
# NB: The `databases` key needs to match the keys in the config file.
databases:
  dev-primary:
    username: root
    password: root
  dev-replica:
    username: root
    password: root
