---
# Auth credentials for the configured databases.
# NB: The `databases` key needs to match the keys in the config file.
databases:
  us1_primary:
    username: persona-web-us1
    password: persona-web-us1
  us1_replica0:
    username: persona-web-us1-ro
    password: persona-web-us1-ro
  us2_primary:
    username: persona-web-us2
    password: persona-web-us2
  us2_replica0:
    username: persona-web-us2-ro
    password: persona-web-us2-ro
