---
# Path to the credentials files; this should be mounted in the pod as a secret from GCSM.
credential_file: configs/credentials.yaml

# Note: all limits are in seconds, and MUST have the 's' suffix
default_config: &default_config # run the check every 1 second
  interval: 1s
  # kill queries that have been running for more than X seconds
  long_query_limit: 2s
  # kill transactions that have been running for more than X seconds
  long_transaction_limit: 60s
  # whether to run in dry run mode; if true, the sniper will only log the queries
  # and transactions that are exceeding the thresholds, but not kill anything
  dry_run: true

# List of databases to watch, and various configuration options for them. The login creds
# are stored in the file defined above, and the keys to each database entry must match.
databases:
  dev-primary:
    address: mysql-us1-primary.mysql.svc.cluster.local
    port: 3306
    schema: web-us1
    <<: *default_config
  dev-replica0:
    address: mysql-us1-replica0.mysql.svc.cluster.local
    port: 3306
    schema: web-us1
    <<: *default_config
  dev-replica1:
    address: mysql-us1-replica1.mysql.svc.cluster.local
    port: 3306
    schema: web-us1
    interval: 10s
    long_query_limit: 60s
    long_transaction_limit: 120s

# Logging configuration; this sets up slog
log:
  # The slog logger level to use. Valid options are "DEBUG", "INFO", "WARN", and "ERROR".
  level: INFO
  # The format of the log output. Valid options are "json" and anything else. If value isnt json, log output will be plain text and colorized.
  format: json
  # Whether to include the caller in the log output.
  include_caller: false
