---
# Auth credentials for the configured databases. This file gets merged with the
# main config file, so that any keys defined here will be merged into the
# `databases` configs in the main config file. As such, the `databases`
# keys need to match the keys in the main config file.
databases:
  dev-primary:
    username: web-us1
    password: web-us1
  dev-replica0:
    username: web-us1-ro0
    password: web-us1-ro0
  dev-replica1:
    username: web-us1-ro1
    password: web-us1-ro1
